name: hl_image_picker
description: Choose images/videos from the library, crop images, and capture new photos/videos with ease.
repository: https://github.com/howljs/hl_image_picker/tree/main/hl_image_picker
issue_tracker: https://github.com/howljs/hl_image_picker/issues

version: 999.2.16

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  hl_image_picker_platform_interface:
    git:
      url: git@github.com:miraclebg/hl_image_picker.git
      ref: main
      path: hl_image_picker_platform_interface
  hl_image_picker_ios:
    git:
      url: git@github.com:miraclebg/hl_image_picker.git
      ref: main
      path: hl_image_picker_ios
  hl_image_picker_android:
    git:
      url: git@github.com:miraclebg/hl_image_picker.git
      ref: main
      path: hl_image_picker_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  plugin_platform_interface: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        default_package: hl_image_picker_android
      ios:
        default_package: hl_image_picker_ios
